### PR TITLE
Updating tor.com stylesheets with castoff variations and some fixes

### PR DESCRIPTION
**Pull request by nelliemckesson**
See https://docs.google.com/document/d/12GCkUhBf9nUb_BhaR1pECJvuBeI9lp-MPqGeSAPkTFw/edit# for an explanation of new files and changes.

Also, it looks like there were a number of new additions made to the source base.scss file before it was handed off to me, that haven't yet been merged into master here.

### CODE REVIEW

**Comment by mattretzer** [comment]
Hi Nellie, 
My bad, I think we should actually have this PR's 'base branch' be macmillanpublishers:sectionstartstaging, that should account for all the unmerged changes in what you were using.. We haven't deployed it yet but we need the CSS you're working on to reflect section starts. 
Sorry I didn't think to mention that sooner, hope there was not too much confusion :( 
I'm going to go ahead and make that change & try some templates out today or tomorrow :)

**Comment by nelliemckesson** [comment]
@mattretzer Ah, makes sense! I don't *think* I added anything that isn't compatible with section starts (and I tested everything using the base branches and sample files that you gave me, and everything was looking good). I'll await your feedback though to see if I need to make any changes! Am I recalling correctly that the section starts don't actually substantially change the final HTML that we're writing CSS for (i.e., it's still mostly standard HTMLBook)?

**Comment by mattretzer** [comment]
Hi Nellie, 
So I reviewed for syntax, tested compiling, and did a few runs; looks great!  I think we're going to let someone from torDOTcom review against specs in greater detail, so this is not the final review alas.

The gridlines are still imported into the .scss's (helpful for my review!) which we can leave in for now since there may be a couple more revisions– as long as one of us remembers to yoink them before merge;)

The only other thing is that when I compile your scss I am getting some minor discrepancies in the css output:  these are trivial, in that they they no effect on pdf output, but it'd be nice to account for &/or eradicate the diffs if its something straightforward.
- your closing curly brackets are on the line following the last element of a rule, which I can emulate by including  '--style expanded' flag in my scss command. So this one is really not a problem as long as you're consistent.
- a bunch of class and data-type strings in your css aren't enclosed in double-quotes (in mine they are). Is this coming from an updated base.scss on your end or a setting somewhere? Here's an [example](https://www.dropbox.com/s/9eae8b2f5b6fd4h/csscompare.zip?dl=0).

**Comment by nelliemckesson** [comment]
@mattretzer I can't figure out why the double-quotes are getting dropped from the compiled CSS--they're definitely still in all the SCSS files. The only thing I can think of is that it's because I'm using the new dart sass (I had to re-install sass and the older versions are no longer supported). I could try to remove the compiled CSS files from the commit if that'll help, and only submit the actual SCSS, and then you can compile on your end. Thoughts?

**Comment by mattretzer** [comment]
Replaced by PR 88

**Pull request closed without merging**
