### PR TITLE
Imprintcss

### PR DESCRIPTION
**Pull request by mattretzer**

### CODE REVIEW

**Comment by mattretzer** [comment]
@nelliemckesson can you please review & merge?

**Comment by nelliemckesson** [comment]
Hey Matt, looks good! A couple little edits though, before I merge:

In pdfmaker/css/symbol/pdf.css and pdfmaker/css/thomas_dunne/pdf.css, you have an extra closing "}" at the end of the file.

For torDOTcom, you should update the image path in the scss (pdfmaker/css/_modules/base.scss), and then regenerate novella.scss as pdf.css, and novel.scss as novel.css. See guidance here: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#using_sass

**Comment by mattretzer** [comment]
Thanks, good catch on the thomas_dunne, and I will do that and the tor bit now :)

**Comment by nelliemckesson** [comment]
👍

**Pull request merged**
